# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jesse Millar
tagline:             'JavaScripter Extraordinaire'
description:         'The personal blog and domain of Jesse Millar.  Cool stuff awaits you.'
url:                 http://www.jessemillar.com/
baseurl:             /

author:
  name:              'Jesse Millar'
  url:               https://twitter.com/jessemillar

paginate:            5
