# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jesse Millar
tagline:             ''
description:         ''
url:                 http://www.jessemillar.com/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Jesse Millar
  url:               https://twitter.com/jessemillar
  email:             jesse@jessemillar.com

# Custom vars
version:             1.0.0
